### ISSUE TITLE
Need your help

### ISSUE THREAD

**Issue by Dickoem** [MacHu-GWU/pyproject_ops-project#1]
Hi, i found your ID from hotkeynet.readthedocs.io and I can read Chinese.
Since the official website has been down,I can't find any download link of the software.
Would you please help me and send me a copy of HotkeyNet.
My email address: 506321006@qq.com  
Thanks!

**Comment by MacHu-GWU** [comment]
@Dickoem 你咋找到这个项目来了.. 咋不在那个项目下留言? 我明天发你一份. 你用来玩什么游戏? 我是用来单刷魔兽世界巫妖王团本.

**Comment by Dickoem** [comment]
主要是玩wow 谢谢你





------------------ Original ------------------
From: Sanhe Hu ***@***.***&gt;
Date: Sat,Jun 3,2023 3:49 PM
To: MacHu-GWU/pyproject_ops-project ***@***.***&gt;
Cc: Dickoem ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [MacHu-GWU/pyproject_ops-project] Need your help (Issue #1)





 
@Dickoem 你咋找到这个项目来了.. 咋不在那个项目下留言? 我明天发你一份. 你用来玩什么游戏? 我是用来单刷魔兽世界巫妖王团本.

**Comment by MacHu-GWU** [comment]
我都不记得了, 我发过你了吗?

**Comment by Dickoem** [comment]
并没有发我。。。


麻烦发我一份吧 谢谢 ~！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MacHu-GWU/pyproject_ops-project"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月5日(星期六) 晚上9:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MacHu-GWU/pyproject_ops-project] Need your help (Issue #1)





 
我都不记得了, 我发过你了吗?

**Comment by MacHu-GWU** [comment]
@Dickoem https://github.com/MacHu-GWU/hotkeynet-project/releases/tag/0.1.4 到这里下载.

**Comment by Dickoem** [comment]
已经下载。感谢无私分享。这软件太老了，而且作者弃坑，我全网找了好久。


再次感谢~！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MacHu-GWU/pyproject_ops-project"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月11日(星期五) 晚上10:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MacHu-GWU/pyproject_ops-project] Need your help (Issue #1)





 
@Dickoem https://github.com/MacHu-GWU/hotkeynet-project/releases/tag/0.1.4 到这里下载.

**Comment by MacHu-GWU** [comment]
不客气, 但是我认为从强大程度上来说 灵活性 可扩展性, 设计模式角度来说, 它是最强的 比 iboxer 强多了. 它的上限极高
